<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://www.oracle.com/soasample"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/OrderToDB"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
                xmlns:client="http://xmlns.oracle.com/OrderToShipment/OrderProcessing/OrderProcess"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/OrderToShipment/OrderProcessing/OrderToDB"
                xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/OrderProcess.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Order" namespace="http://www.oracle.com/soasample"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/OrderToDB.wsdl"/>
        <oracle-xsl-mapper:rootElement name="OrdersCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/OrderToDB"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI FEB 19 23:36:06 IST 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:OrdersCollection>
      <tns:Orders>
        <tns:orderNumber>
          <xsl:value-of select="/ns0:Order/ns0:OrderNumber"/>
        </tns:orderNumber>
        <tns:sessionid>
          <xsl:value-of select="/ns0:Order/ns0:SessionID"/>
        </tns:sessionid>
        <xsl:if test="/ns0:Order/ns0:OrderDate">
          <tns:orderDate>
            <xsl:value-of select="/ns0:Order/ns0:OrderDate"/>
          </tns:orderDate>
        </xsl:if>
        <tns:totalAmount>
          <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:AuthorizationAmount"/>
        </tns:totalAmount>
        <tns:email>
          <xsl:value-of select="/ns0:Order/ns0:Email"/>
        </tns:email>
        <xsl:if test="/ns0:Order/ns0:Status">
          <tns:status>
            <xsl:value-of select="/ns0:Order/ns0:Status"/>
          </tns:status>
        </xsl:if>
        <tns:orderItemsCollection>
          <xsl:for-each select="/ns0:Order/ns0:Items/ns0:Item">
            <tns:OrderItems>
              <tns:itemId>
                <xsl:value-of select="position ( )"/>
              </tns:itemId>
              <tns:sku>
                <xsl:value-of select="ns0:SKU"/>
              </tns:sku>
              <tns:quantity>
                <xsl:value-of select="ns0:Quantity"/>
              </tns:quantity>
              <tns:unitprice>
                <xsl:value-of select="ns0:UnitPrice"/>
              </tns:unitprice>
              <tns:brand>
                <xsl:value-of select="ns0:Brand"/>
              </tns:brand>
              <tns:model>
                <xsl:value-of select="ns0:Model"/>
              </tns:model>
              <tns:categoryId>
                <xsl:value-of select="ns0:Category"/>
              </tns:categoryId>
              <tns:description>
                <xsl:value-of select="ns0:Description"/>
              </tns:description>
            </tns:OrderItems>
          </xsl:for-each>
        </tns:orderItemsCollection>
        <tns:shippinginfoCollection>
          <tns:Shippinginfo>
            <tns:shippingId>
              <xsl:value-of select="/ns0:Order/ns0:OrderNumber"/>
            </tns:shippingId>
            <tns:shipmethod>
              <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:ShipMethod"/>
            </tns:shipmethod>
            <tns:shipspeed>
              <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:ShippingSpeed"/>
            </tns:shipspeed>
            <tns:addressId>
              <tns:addressId>
                <xsl:value-of select="/ns0:Order/ns0:OrderNumber"/>
              </tns:addressId>
              <tns:firstName>
                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:FirstName"/>
              </tns:firstName>
              <tns:lastName>
                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:LastName"/>
              </tns:lastName>
              <tns:addressLine1>
                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:AddressLine"/>
              </tns:addressLine1>
              <tns:addressLine2>
                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:AddressLine"/>
              </tns:addressLine2>
              <tns:city>
                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:City"/>
              </tns:city>
              <tns:state>
                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:State"/>
              </tns:state>
              <tns:zipCode>
                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:ZipCode"/>
              </tns:zipCode>
              <tns:phone>
                <xsl:value-of select="/ns0:Order/ns0:Shipping/ns0:Address/ns0:PhoneNumber"/>
              </tns:phone>
            </tns:addressId>
          </tns:Shippinginfo>
        </tns:shippinginfoCollection>
        <tns:billinginfoCollection>
          <tns:Billinginfo>
            <tns:billingId>
              <xsl:value-of select="/ns0:Order/ns0:OrderNumber"/>
            </tns:billingId>
            <tns:cardpaymenttype>
              <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:CardPaymentType"/>
            </tns:cardpaymenttype>
            <tns:cardnum>
              <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:CardNum"/>
            </tns:cardnum>
            <tns:expiredate>
              <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:ExpireDate"/>
            </tns:expiredate>
            <tns:cardname>
              <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:CardName"/>
            </tns:cardname>
            <tns:authorizationdate>
              <xsl:value-of select="/ns0:Order/ns0:Billing/ns0:AuthorizationDate"/>
            </tns:authorizationdate>
          </tns:Billinginfo>
        </tns:billinginfoCollection>
      </tns:Orders>
    </tns:OrdersCollection>
  </xsl:template>
</xsl:stylesheet>
