<wsdl:definitions
     name="GetShipmentDetails"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OrderToShipment/OrderFulfillment/GetShipmentDetails"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OrderToShipment/OrderFulfillment/GetShipmentDetails"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetShipmentDetails"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="GetShipmentDetails_plt" >
    <plt:role name="GetShipmentDetails_role" >
      <plt:portType name="tns:GetShipmentDetails_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/GetShipmentDetails" schemaLocation="../Schemas/GetShipmentDetails_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="GetShipmentDetailsSelect_inputParameters">
        <wsdl:part name="GetShipmentDetailsSelect_inputParameters" element="top:GetShipmentDetailsSelect_ShipmentMethodInputParameters"/>
    </wsdl:message>
    <wsdl:message name="ShippingMethodsCollection_msg">
        <wsdl:part name="ShippingMethodsCollection" element="top:ShippingMethodsCollection"/>
    </wsdl:message>
    <wsdl:portType name="GetShipmentDetails_ptt">
        <wsdl:operation name="GetShipmentDetailsSelect">
            <wsdl:input message="tns:GetShipmentDetailsSelect_inputParameters"/>
            <wsdl:output message="tns:ShippingMethodsCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
