<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
     name="PackAndShipProcess"
     targetNamespace="http://xmlns.oracle.com/OrderToShipment/PackAndShip/PackAndShipProcess"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
     xmlns:client="http://xmlns.oracle.com/OrderToShipment/PackAndShip/PackAndShipProcess"
     xmlns:ns1="http://www.oracle.com/soasample"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    >
    <wsdl:documentation>
        <abstractWSDL>http://127.0.0.1:7001/soa-infra/services/default/PackAndShip!1.0/WSDLs/PackAndShipProcess.wsdl</abstractWSDL>
    </wsdl:documentation>
    <plnk:partnerLinkType name="PackAndShipProcess">
        <plnk:role name="PackAndShipProcessProvider" portType="client:PackAndShipProcess"/>
    </plnk:partnerLinkType>
    <wsdl:types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema">
            <import namespace="http://www.oracle.com/soasample" schemaLocation="oramds:/apps/soa/Schemas/CanonicalOrder.xsd"/>
        </schema>
    </wsdl:types>
    <wsdl:message name="PackAndShipProcessRequestMessage">
        <wsdl:part name="payload" element="ns1:Shipping"/>
    </wsdl:message>
    <wsdl:portType name="PackAndShipProcess">
        <wsdl:operation name="process">
            <wsdl:input message="client:PackAndShipProcessRequestMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="PackAndShipProcessBinding" type="client:PackAndShipProcess">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="process">
            <soap:operation style="document" soapAction="process"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="packandshipprocess_client_ep">
        <wsdl:port name="PackAndShipProcess_pt" binding="client:PackAndShipProcessBinding">
            <soap:address location="http://127.0.0.1:7001/soa-infra/services/default/PackAndShip/packandshipprocess_client_ep"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>
