<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="ValidateCrCard"
     targetNamespace="http://xmlns.oracle.com/ServiceBusApplication/ValidateCC/ValidateCrCard"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:WL5G3N2="http://xmlns.oracle.com/ServiceBusApplication/ValidateCC/ValidateCrCard"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="ValidateCreditCard">
        <plnk:role name="execute_ptt" portType="WL5G3N2:execute_ptt"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://xmlns.oracle.com/ServiceBusApplication/ValidateCC/ValidateCrCard"
         location="http://127.0.0.1:7001/ValidateCC/ValidateCrCardProxyService?wsdl"/>
</wsdl:definitions>
